docs/working-agreement.md
src/docs/working-agreement.md

This is a draft of the working agreement. I tried to adapt it from a full-time team to our part-time situation. 
It raises a few questions: 
- how do we handle sprint ceremonies (demo, retro, planning, grooming)
- how do we handle sizing of user stories for sprint planning. 
There is a lot in the doc. I consider it mostly a north star. Please add comments, objections, and additions. 
https://das-ph-inventory-tracker.atlassian.net/browse/PIT-79
- Closes #

initial draft of working agreement

---

docs/designs/login-design.md

I updated the login design doc based on [maarten/96-login-design](https://github.com/digitalaidseattle/plymouth-housing/tree/maarten/96-login-design). Add some needed features and questions, including the reset PIN flow for further discussion.
[PIT-96](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-96?atlOrigin=eyJpIjoiZjhiMmMxMmQyMDU5NGI4MWEyYzdlNzVlMWJiZGFjMzYiLCJwIjoiaiJ9)

Update of the login design document

---

docs/arch-design-template.md

Arch design template to be used for each implementation story. 
https://das-ph-inventory-tracker.atlassian.net/jira/core/projects/PIT/board?selectedIssue=PIT-100

initial attempt for arch design template

---

.github/workflows/azure-swa.yml
src/pages/authentication/Login.tsx

This is a test branch to deploy the app so that we can debug the login flow. 
124
nothing yet

Bug: fail on login

---

.github/workflows/azure-static-web-apps-CD.yml
.github/workflows/azure-static-web-apps-CI.yml
.github/workflows/azure-swa.yml

We need a stable staging environment to make sure that code changes will work in main. 
Current issue with github deployment is that it creates a new environment for every merge with a new URL. That poses issues for the redirect URI that needs to be set up in Entra ID registration
Jira 128
- Closes #
Make sure that OAuth redirect works from staging.

Staging environment test

---

.github/workflows/azure-static-web-apps-CD.yml
.github/workflows/azure-static-web-apps-CI.yml

_Give a brief context and description of the code change. Highlight anything you want reviewers to pay attention to._
_The PR should have enough information so someone coming in fresh gets a sense of what's going on, but the details of the overall project can be documented on project.digitalaidseattle.org_
- Closes #

next try for staging

---

src/pages/authentication/EnterPinPage.tsx
src/pages/authentication/Login.tsx
src/pages/authentication/PickNamePage.tsx

Update the button color of PickNamePage and EnterPinPage to black to match the latest Figma design.
- Related Issue # [PIT-121](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-121)

update button color of PickNamePage and EnterPinPage

---

src/data/volunteers.tsx
src/pages/VolunteerHome/index.tsx
src/pages/authentication/PickNamePage.tsx
src/pages/routes.tsx

basic volunteer home page without volunteer account switching and session timeout features
- Related Issue # [PIT-122](https://das-ph-inventory-tracker.atlassian.net/jira/core/projects/PIT/board?selectedIssue=PIT-122)
Screenshots

basic volunteer home page

---

src/data/volunteers.tsx
src/layout/MainLayout/Header/HeaderContent/Profile/index.tsx
src/layout/MainLayout/Header/HeaderContent/VolunteerSwitcher.tsx
src/layout/MainLayout/Header/HeaderContent/index.tsx
src/pages/VolunteerHome/index.tsx
src/pages/authentication/Login.tsx
src/pages/authentication/PickNamePage.tsx
src/pages/inventory/index.tsx
src/sections/tickets/TicketDialog.tsx
src/sections/tickets/TicketToolbarItem.tsx

A basic volunteer dropdown in the header for volunteers to switch accounts. Clicking a different name will direct the user to the "pick-your-name" page. Names will be fetched from the server, which has not been built yet.
- Related Issue #[122](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-122?atlOrigin=eyJpIjoiMTNlMTljY2FiMjUzNDk4YTllYmY0YjU1NDg5YjI0ZDAiLCJwIjoiaiJ9)

Basic volunteer dropdown in the header

---

src/pages/authentication/auth-forms/AzureAuth.test.tsx

test cases for authentication
- Related Issue [PIT-141](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-141)
- Closes #

add auth test cases

---

.github/workflows/azure-static-web-apps-CI.yml
src/layout/MinimalLayout/MinimalFooter.tsx

The PR removes the GitHub and Privacy Policy links in the footer on the 'Pick Your Name' page when logging in as a volunteer.
[PIT-165](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-165)
It has been tested locally, and the screenshot has been attached to the user story.

#165 Remove links in footer

---

src/menu-items/index.tsx

The PR hides dashboard page for admin 
[PIT-169](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-169)
It has been tested locally, and the screenshot has been attached to the user story.

#169 Hide dashboard on admin

---

docs/designs/business-rules-design.md
docs/designs/inventory-design.md

This is a design for the business rules for checkout. It requires a change in database schema since categories table needs to be created. 
Built on the items table and design doc. 
#186
Please check the design and provide feedback if I am missing something.

business rule design

---

package.json

Testing versioning release
- Closes #

updating release version in package.json

---

.github/workflows/azure-static-web-apps-prod.yml

_Give a brief context and description of the code change. Highlight anything you want reviewers to pay attention to._
_The PR should have enough information so someone coming in fresh gets a sense of what's going on, but the details of the overall project can be documented on project.digitalaidseattle.org_
- Closes #

fix version trigger

---

.github/workflows/azure-static-web-apps-prod.yml

_Give a brief context and description of the code change. Highlight anything you want reviewers to pay attention to._
_The PR should have enough information so someone coming in fresh gets a sense of what's going on, but the details of the overall project can be documented on project.digitalaidseattle.org_
- Closes #

sync with CD

---

src/pages/authentication/PickNamePage.tsx

- Add loading state to input label
- Add error notification via Snackbar
- Related Issue #[PIT-188](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-188)

#188 Add loading and error handling to PickYourNamePage

---

docs/setup-guide.md

The update to the doc reflects the change in the workflow files. I had to update those outside the normal PR approval process for efficiency reasons. Please check them for accuracy though. Thanks!!
#189

189 updating pipelines and docs

---

database/bootstrap_db.ps1
docs/setup-guide.md

To facilitate recreation of the db, here are some PS scripts. Instructions are in the updated documentation. 
#191

built db creation scripts

---

src/layout/MainLayout/Header/HeaderContent/Profile/index.tsx

The PR fixes the following issues:
- Remove "Dude" text and change it to the role (admin or volunteer)
- Add a “Log out” to the right of the Logout icon
- Remove the white space under the logout icon. 
[PIT-182](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-182)
It has been tested locally, and the screenshot has been attached to the user story.

#182 Fix profile

---

.github/dependabot.yaml

We should leverage [dependabot ](https://github.blog/news-insights/product-news/keep-all-your-packages-up-to-date-with-dependabot/)to help us keep our dependency tree up to date. 
[214 ](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-214)
[118](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-118?atlOrigin=eyJpIjoiNjIyNzI0MzkzZmRkNGIwMGI2ZTY2ZDE1OTU4NWRlMDQiLCJwIjoiaiJ9)
This yaml file should weekly check for new package updates and create automatic PRs.

creating dependabot file

---

docs/setup-guide.md

update database setup guide for macOS
[PIT-216](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-216)

PING/PIT-216 update database setup guide for macOS

---

src/components/Checkout/CheckoutAPICalls.tsx

_Give a brief context and description of the code change. Highlight anything you want reviewers to pay attention to._
_The PR should have enough information so someone coming in fresh gets a sense of what's going on, but the details of the overall project can be documented on project.digitalaidseattle.org_
- Closes #

adding message parameter to StoredProc API call.

---

docs/setup-guide.md

Since I am using macOS for development at the moment, I found that SQL Server does not support macOS unless using Docker. Therefore, I updated the setup guide for the local database on macOS.
- Closes # [pit-227](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-227)

ping/227 update setup guild for the local database on macOS

---

database/procedures/process_checkout.sql
database/procedures/process_welcome_basket_checkout.sql
database/tests/test_checkout_basket.sql
database/tests/test_checkout_welcome_basket.sql

Inventory is now allowed to go negative
#252
Please test by checking out an item that is close to 0 and see if it can go negative.

commenting out negative inventory check

---

docs/designs/appliance-tracking-design.md
docs/designs/arch-design-template.md

This design doc should give enough details for implementing the item tracking feature. 
- Closes #260
NA

Architecture design for appliance tracking

---

docs/help/update-descriptions.md

This is a help file for PH so they can update descriptions for items in the database themselves. 
- Closes #314

adding help file to update description

---

src/pages/authentication/CenteredLayout.tsx
src/pages/authentication/EnterPinPage.tsx
src/pages/authentication/PickNamePage.tsx

The MUI update from a few weeks ago, caused some other changes on the volunteer login pages. @siberden found them. This PR aims to make the login experience for volunteers consistent across the two pages. 
Closes #319
Before:
After:

Fixing pick-name and enterpin UI

---

src/pages/VolunteerHome/index.tsx

Changed wording on Volunteer home page for Inventory. 
- Closes [#323](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-323?atlOrigin=eyJpIjoiOGFlZGY0YjVlNTFhNDRjMDhlOTkwMTc1NWExOGIzMzMiLCJwIjoiaiJ9)

changed wording for home page
